name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: jakejarvis/s3-sync-action@main
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.sumoactionsdev }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AKIAWSDPBPS3QI5TAUZA }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.35BxE6G0nMtZtq/Rl6+4g7Os+FaDjF9NUq21asoS }}
        AWS_REGION: 'ap-southeast-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'public'      # optional: defaults to entire repository
